version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tests"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "chore"
      - "patch"

  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "chore"
      - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "chore"
      - "patch"
include-labels:
  - 'feature'
  - 'enhancement'
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'chore'
