repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-yaml
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
      - id: gradle-build
  - repo: local
    hooks:
      - id: groovy-lint
        name: Groovy Lint
        language: docker_image
        entry: nvuillam/npm-groovy-lint
        args: ['--failon', 'warning', '-l' , 'warning', '-f', '**/*.groovy']
        files: .*\.groovy
        pass_filenames: false
