name: Release

on:
  pull_request:
    types: closed

jobs:
  develop:
    name: Create RC
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.base_ref == 'develop'
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          ref: 'develop'

      - name: Create Tag
        uses: K-Phoen/semver-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_branch: develop
          tag_format: v%major%.%minor%.%patch%-RC
          release_strategy: tag
      
      - name: Create Release
        if: steps.create_tag.outputs.tag
        uses: Roang-zero1/github-create-release-action@master
        with:
          created_tag: ${{ steps.tag_and_prepare_release.outputs.tag }}
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          prerelease_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+-RC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}