name: Docker

on:
  push:
    tags:
      - '*'
    paths:
      - 'docker/prod/*'

jobs:
  prod:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: prod_image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "dsty/jenkins:${{ contains(github.ref_name, 'SNAPSHOT') && github.ref_name || 'latest' }}"
          file: docker/prod/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dsty/jenkins:demo
          file: docker/dev/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "baseImage=${{ steps.prod_image.outputs.digest }}"
