name: Lint

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Groovy Linter
        uses: docker://nvuillam/npm-groovy-lint