name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    paths:
      - '*gradle*'
      - '.github/workflows/test.yml'
      - '.groovylintrc.json'
      - '.pre-commit-config.yaml'
      - 'jobs/**'
      - 'src/**'
      - 'tests/**'
      - 'docker/**'

jobs:
  debug:
    name: Debug docker
    runs-on: ubuntu-latest
    steps:
      - run: docker info

  linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v1.2.0
        with:
          fossa-api-key: 7c94ee8610054ec8084c954b58615e0e

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Python Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('tests/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r tests/requirements.txt

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

  tests:
    name: Functional
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Python Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('tests/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r tests/requirements.txt

      - name: Test with pytest
        run: pytest
