name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    paths-ignore:
      - '.github/workflows/release.yml '

jobs:
  pr:
    name: PR is Valid
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
            github-token: '${{ secrets.GITHUB_TOKEN }}'
            valid-labels: 'major, minor, patch'

  linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Groovy Linter
        uses: docker://nvuillam/npm-groovy-lint
        with:
          entrypoint: npm-groovy-lint
          args: --failon warning -l warning -p src

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

  tests:
    name: Functional
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_PUSH_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}

      - name: Test with pytest
        env:
          RUNNER_IMAGE: shadycuz/jenkins-std-lib
        run: |
          pytest
