name: Tests

on: [push, pull_request]

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run Tests
        run: ./gradlew build --no-daemon

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Groovy Linter
        uses: docker://nvuillam/npm-groovy-lint
        with:
          entrypoint: npm-groovy-lint
          args: --failon warning -l warning 