name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    paths-ignore:
      - '.github/workflows/release.yml'
      - '.github/workflows/pr_label.yml'

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

  tests:
    name: Functional
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Test with pytest
        run: pytest
